[package]
name = "shouxtech/waitfor"
description = "Wait for data with a timeout"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.5.0"
Trove = "sleitnick/trove@0.5.0"