[package]
name = "shouxtech/waitfor"
description = "Wait for data with a timeout"
version = "0.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
Trove = "sleitnick/trove@1.5.0"
